version: '2.3'

services:
  app:
    build: .
    ports:
      - "6060:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./app:/data/app"
      - "/data/app/node_modules/"
    environment:
      NODE_ENV: "development"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_HOST: "db"

  db:
    image: dev-docker.netkey.at:5000/mysql:5.7
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    healthcheck:
      test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASS} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 30
    volumes:
      - "./data/mysql:/var/lib/mysql"


  adminer:
    image: dev-docker.netkey.at:5000/netkey/adminer
    ports:
      - "8096:80"