version: '2.3'

services:
  app:
    build: .
    ports:
      - "6060:3000"
    depends_on:
      - db
    volumes:
      - "./app:/data/app"
      - "/data/app/node_modules/"
  db:
    image: dev-docker.netkey.at:5000/mysql:5.7
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - "./data/mysql:/var/lib/mysql"

  adminer:
    image: dev-docker.netkey.at:5000/netkey/adminer
    ports:
      - "8096:80"

 #/bin/sh/node_modules/.bin npx knex migrate:latest